{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2025-48459",
        "assignerOrgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
        "state": "PUBLISHED",
        "assignerShortName": "apache",
        "dateReserved": "2025-05-22T06:25:16.580Z",
        "datePublished": "2025-09-24T07:57:24.444Z",
        "dateUpdated": "2025-09-24T07:57:24.444Z"
    },
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unaffected",
                    "product": "Apache IoTDB",
                    "vendor": "Apache Software Foundation",
                    "versions": [
                        {
                            "lessThan": "2.0.5",
                            "status": "affected",
                            "version": "1.0.0",
                            "versionType": "semver"
                        }
                    ]
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "type": "finder",
                    "value": "Sanny"
                },
                {
                    "lang": "en",
                    "type": "finder",
                    "value": "75Acol"
                },
                {
                    "lang": "en",
                    "type": "finder",
                    "value": "stan fang"
                },
                {
                    "lang": "en",
                    "type": "finder",
                    "value": "Wu Jiang"
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "supportingMedia": [
                        {
                            "base64": false,
                            "type": "text/html",
                            "value": "<p>Deserialization of Untrusted Data vulnerability in Apache IoTDB.</p><p>This issue affects Apache IoTDB: from 1.0.0 before 2.0.5.</p><p>Users are recommended to upgrade to version 2.0.5, which fixes the issue.</p>"
                        }
                    ],
                    "value": "Deserialization of Untrusted Data vulnerability in Apache IoTDB.\n\nThis issue affects Apache IoTDB: from 1.0.0 before 2.0.5.\n\nUsers are recommended to upgrade to version 2.0.5, which fixes the issue."
                }
            ],
            "metrics": [
                {
                    "other": {
                        "content": {
                            "text": "moderate"
                        },
                        "type": "Textual description of severity"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-502",
                            "description": "CWE-502 Deserialization of Untrusted Data",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
                "shortName": "apache",
                "dateUpdated": "2025-09-24T07:57:24.444Z"
            },
            "references": [
                {
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://lists.apache.org/thread/mr84n19nv8d0bmcrfsj3mm5ff5qn4q2f"
                }
            ],
            "source": {
                "discovery": "UNKNOWN"
            },
            "title": "Apache IoTDB: Deserialization of untrusted Data",
            "x_generator": {
                "engine": "Vulnogram 0.2.0"
            }
        }
    }
}