{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2025-48392",
        "assignerOrgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
        "state": "PUBLISHED",
        "assignerShortName": "apache",
        "dateReserved": "2025-05-20T01:52:06.367Z",
        "datePublished": "2025-09-24T07:59:52.592Z",
        "dateUpdated": "2025-09-24T07:59:52.592Z"
    },
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unaffected",
                    "product": "Apache IoTDB",
                    "vendor": "Apache Software Foundation",
                    "versions": [
                        {
                            "lessThanOrEqual": "1.3.4",
                            "status": "affected",
                            "version": "1.3.3",
                            "versionType": "semver"
                        },
                        {
                            "lessThanOrEqual": "2.0.4",
                            "status": "affected",
                            "version": "2.0.1-beta",
                            "versionType": "semver"
                        }
                    ]
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "type": "finder",
                    "value": "yyjLF"
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "supportingMedia": [
                        {
                            "base64": false,
                            "type": "text/html",
                            "value": "<p>A vulnerability in Apache IoTDB.</p><p>This issue affects Apache IoTDB: from 1.3.3 through 1.3.4, from 2.0.1-beta through 2.0.4.</p><p>Users are recommended to upgrade to version 2.0.5, which fixes the issue.</p>"
                        }
                    ],
                    "value": "A vulnerability in Apache IoTDB.\n\nThis issue affects Apache IoTDB: from 1.3.3 through 1.3.4, from 2.0.1-beta through 2.0.4.\n\nUsers are recommended to upgrade to version 2.0.5, which fixes the issue."
                }
            ],
            "metrics": [
                {
                    "other": {
                        "content": {
                            "text": "moderate"
                        },
                        "type": "Textual description of severity"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "DoS Vulnerability",
                            "lang": "en"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
                "shortName": "apache",
                "dateUpdated": "2025-09-24T07:59:52.592Z"
            },
            "references": [
                {
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://lists.apache.org/thread/1rn0637hptglmctf8cqd9425bj4q21td"
                }
            ],
            "source": {
                "discovery": "UNKNOWN"
            },
            "title": "Apache IoTDB: DoS Vulnerability",
            "x_generator": {
                "engine": "Vulnogram 0.2.0"
            }
        }
    }
}